package com.emailssummarizer.apirs.message;

import jakarta.persistence.*;
import java.util.UUID;

/**
 * JPA entity representing an individual email message.
 *
 * <p>Maps to the {@code MESSAGE} database table. Each message belongs to exactly one
 * {@link com.emailssummarizer.apirs.category.Category}, referenced by the {@code categoryCode}
 * foreign key. The primary key is a UUID generated by the database at insert time.
 *
 * <p>The {@code body} field is stored as a {@code CLOB} to support large message content.
 *
 * @see MessageService
 * @see MessageRepository
 */
@Entity
@Table(name = "MESSAGE")
public class Message {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(columnDefinition = "UUID")
    private UUID id;

    @Column(nullable = false)
    private String title;

    @Lob
    @Column
    private String body;

    @Column(name = "category_code", nullable = false)
    private String categoryCode;

    /**
     * Required no-argument constructor for JPA.
     */
    public Message() {}

    /**
     * Returns the UUID primary key of this message.
     *
     * @return the auto-generated {@link UUID}, or {@code null} before the entity is persisted
     */
    public UUID getId() { return id; }

    /**
     * Sets the UUID primary key of this message.
     *
     * <p>This method exists for JPA and testing purposes; application code should not
     * set the {@code id} directly.
     *
     * @param id  the UUID to assign
     */
    public void setId(UUID id) { this.id = id; }

    /**
     * Returns the subject line of this message.
     *
     * @return the message title; never {@code null} for a persisted message
     */
    public String getTitle() { return title; }

    /**
     * Sets the subject line of this message.
     *
     * @param title  the new title; must not be {@code null}
     */
    public void setTitle(String title) { this.title = title; }

    /**
     * Returns the full body content of this message.
     *
     * @return the message body, stored as a {@code CLOB}; may be {@code null}
     */
    public String getBody() { return body; }

    /**
     * Sets the full body content of this message.
     *
     * @param body  the new body content; may be {@code null}
     */
    public void setBody(String body) { this.body = body; }

    /**
     * Returns the code of the {@link com.emailssummarizer.apirs.category.Category}
     * this message belongs to.
     *
     * <p>This is a foreign key reference to {@code CATEGORY.code}. The referenced
     * category must exist; deletion of a category is blocked while messages still
     * reference it.
     *
     * @return the category code; never {@code null} for a persisted message
     */
    public String getCategoryCode() { return categoryCode; }

    /**
     * Sets the category code that this message belongs to.
     *
     * @param categoryCode  the code of an existing category; must not be {@code null}
     */
    public void setCategoryCode(String categoryCode) { this.categoryCode = categoryCode; }
}
